language: cpp
compiler: clang

# install cmake

addons:
  apt:
    packages:
    - cmake
    sources:
    - sourceline: 'https://github.com/L2Program/FlintPlusPlus.git'


# which branches to build
branches:
  only:
  - master
  - develop

# recieve email notifications
# you can edit the emails below if you want to stop or change notifications
notifications:
  email:
    - rashadse@hotmail.com
    - Madisen@sendify.se
    - sarahaldelame88@gmail.com
    - gusthomaa@student.gu.se
