version: '2'
services:
    odsupercomponent:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        network_mode: "host"
        restart: always
        volumes:
        - .:/opt/miniature.data
        command: "/opt/od4/bin/odsupercomponent --cid=180 --verbose=1 --configuration=/opt/miniature.data/configuration"

    proxy-miniature-pwm-motor:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        depends_on:
        - odsupercomponent
        network_mode: "host"
        restart: always
        privileged: true
        volumes:
        - /sys/:/sys/
        - /dev/:/dev/
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-pwm-motor --cid=180 --freq=50 --id=1"
        
        
        # PS4 controller microservice
    proxy-miniature-ps4controller:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        network_mode: "host"
        restart: always
        devices:
        - "/dev/input/js0:/dev/input/js0"
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-ps4controller --cid=180 --freq=10 --verbose=1"    
        
        # Visualisation microservice
    web-interface:
        image: chalmersrevere/opendlv-signal-viewer-multi:v0.0.4
        network_mode: "host"
        ports:
        - "8080:8080"
        restart: always
        privileged: true
        command: "--cid=182"

    # Your microservice.
    example:
        image: group7/carcode
        depends_on:
        - proxy-miniature-pwm-motor
        network_mode: "host"
        restart: always # maybe running only once is enough?
        command: "/opt/CarServices-V2VService"
